// In-memory store with rich demo data for EFFF Club Dashboard
import type {
  User,
  Doctor,
  Appointment,
  Report,
  CommunityPost,
  Comment,
  MessageThread,
  Message,
  Webinar,
  SipPlan,
  LoanOffer,
  SupportTicket,
  Notification,
  PatientSummary,
} from "../types";

// ── USERS ──────────────────────────────────────────────────────────────────
export const users: User[] = [
  {
    id: 1,
    email: "user@efffclub.com",
    password: "password123",
    name: "Priya Sharma",
    role: "user",
    membershipPlan: "platinum",
    journeyStage: "Consultation Pending",
    nextAction: "Upload your AMH blood report.",
    phone: "+91 98765 43210",
    city: "Mumbai",
    area: "Dadar",
    avatarUrl: null,
    createdAt: "2024-11-15T10:00:00Z",
  },
  {
    id: 2,
    email: "doctor@efffclub.com",
    password: "password123",
    name: "Dr. Jatin Shah",
    role: "doctor",
    membershipPlan: "femmeelite",
    journeyStage: "Active",
    nextAction: null,
    phone: "+91 98765 11111",
    city: "Mumbai",
    area: "Colaba",
    avatarUrl: null,
    createdAt: "2024-09-01T09:00:00Z",
  },
  {
    id: 3,
    email: "admin@efffclub.com",
    password: "password123",
    name: "EFFF Admin",
    role: "admin",
    membershipPlan: "femmeelite",
    journeyStage: "Active",
    nextAction: null,
    phone: "+91 98765 00000",
    city: "Mumbai",
    area: "Bandra",
    avatarUrl: null,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: 4,
    email: "ananya@efffclub.com",
    password: "password123",
    name: "Ananya Iyer",
    role: "user",
    membershipPlan: "gold",
    journeyStage: "Reports Submitted",
    nextAction: "Schedule your doctor consultation.",
    phone: "+91 98765 22222",
    city: "Bangalore",
    area: "Koramangala",
    avatarUrl: null,
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: 5,
    email: "meera@efffclub.com",
    password: "password123",
    name: "Meera Nair",
    role: "user",
    membershipPlan: "basic",
    journeyStage: "Awareness",
    nextAction: "Complete your fertility profile to get started.",
    phone: "+91 98765 33333",
    city: "Chennai",
    area: "Adyar",
    avatarUrl: null,
    createdAt: "2025-02-20T10:00:00Z",
  },
  {
    id: 6,
    email: "kavita@efffclub.com",
    password: "password123",
    name: "Kavita Reddy",
    role: "user",
    membershipPlan: "femmeelite",
    journeyStage: "Egg Freezing",
    nextAction: "Review your frozen egg storage agreement.",
    phone: "+91 98765 44444",
    city: "Hyderabad",
    area: "Jubilee Hills",
    avatarUrl: null,
    createdAt: "2024-08-05T10:00:00Z",
  },
];

// ── DOCTORS ────────────────────────────────────────────────────────────────
export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Jatin Shah",
    specialty: "Reproductive Endocrinology & Infertility",
    city: "Mumbai",
    area: "Colaba",
    languages: ["English", "Hindi", "Marathi"],
    consultationModes: ["in-person", "video"],
    rating: 4.9,
    experienceYears: 18,
    avatarUrl: null,
    bio: "Dr. Shah is a leading fertility specialist with over 18 years of experience. He specializes in egg freezing, IVF, and advanced reproductive technologies.",
    availableSlots: 3,
  },
  {
    id: 2,
    name: "Dr. Sunita Rao",
    specialty: "Obstetrics & Gynecology",
    city: "Mumbai",
    area: "Bandra",
    languages: ["English", "Hindi", "Kannada"],
    consultationModes: ["in-person", "video", "phone"],
    rating: 4.7,
    experienceYears: 14,
    avatarUrl: null,
    bio: "Dr. Rao brings compassionate care and cutting-edge expertise in fertility preservation for women across all age groups.",
    availableSlots: 5,
  },
  {
    id: 3,
    name: "Dr. Preethi Menon",
    specialty: "Fertility & IVF Specialist",
    city: "Bangalore",
    area: "Indiranagar",
    languages: ["English", "Kannada", "Tamil"],
    consultationModes: ["in-person", "video"],
    rating: 4.8,
    experienceYears: 12,
    avatarUrl: null,
    bio: "Dr. Menon is renowned for her patient-first approach and exceptional success rates in fertility preservation.",
    availableSlots: 2,
  },
  {
    id: 4,
    name: "Dr. Aisha Khan",
    specialty: "Reproductive Medicine",
    city: "Delhi",
    area: "South Delhi",
    languages: ["English", "Hindi", "Urdu"],
    consultationModes: ["in-person", "video", "phone"],
    rating: 4.6,
    experienceYears: 10,
    avatarUrl: null,
    bio: "Dr. Khan specializes in non-invasive fertility assessment and personalized egg freezing programs.",
    availableSlots: 4,
  },
];

// ── APPOINTMENTS ───────────────────────────────────────────────────────────
export const appointments: Appointment[] = [
  {
    id: 1,
    userId: 1,
    userName: "Priya Sharma",
    doctorId: 1,
    doctorName: "Dr. Jatin Shah",
    status: "approved",
    city: "Mumbai",
    area: "Dadar",
    language: "Hindi",
    mode: "in-person",
    preferredDate: "2025-07-10T11:00:00Z",
    confirmedDate: "2025-07-10T11:00:00Z",
    notes: "First fertility consultation. AMH test pending.",
    doctorNotes: "Please bring all previous reports. Fasting required.",
    createdAt: "2025-07-01T09:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    userName: "Priya Sharma",
    doctorId: 1,
    doctorName: "Dr. Jatin Shah",
    status: "pending",
    city: "Mumbai",
    area: "Dadar",
    language: "Hindi",
    mode: "video",
    preferredDate: "2025-07-20T15:00:00Z",
    confirmedDate: null,
    notes: "Follow-up after AMH report.",
    doctorNotes: null,
    createdAt: "2025-07-03T10:00:00Z",
  },
  {
    id: 3,
    userId: 4,
    userName: "Ananya Iyer",
    doctorId: 2,
    doctorName: "Dr. Sunita Rao",
    status: "completed",
    city: "Bangalore",
    area: "Koramangala",
    language: "Kannada",
    mode: "in-person",
    preferredDate: "2025-06-25T10:00:00Z",
    confirmedDate: "2025-06-25T10:00:00Z",
    notes: "Initial consultation.",
    doctorNotes: "Recommended AMH, FSH, and AFC tests. Excellent candidate for egg freezing.",
    createdAt: "2025-06-20T08:00:00Z",
  },
  {
    id: 4,
    userId: 6,
    userName: "Kavita Reddy",
    doctorId: 1,
    doctorName: "Dr. Jatin Shah",
    status: "rescheduled",
    city: "Mumbai",
    area: "Dadar",
    language: "English",
    mode: "video",
    preferredDate: "2025-07-15T14:00:00Z",
    confirmedDate: "2025-07-17T14:00:00Z",
    notes: "Pre-procedure check.",
    doctorNotes: "Rescheduled due to doctor's travel. New slot confirmed.",
    createdAt: "2025-06-28T11:00:00Z",
  },
];

// ── REPORTS ────────────────────────────────────────────────────────────────
export const reports: Report[] = [
  {
    id: 1,
    userId: 1,
    userName: "Priya Sharma",
    type: "amh",
    fileName: "AMH_Report_Priya_June2025.pdf",
    fileUrl: "/uploads/amh-report-1.pdf",
    uploadedAt: "2025-06-28T09:00:00Z",
    doctorNotes: null,
    recommendations: null,
    isLabBooked: false,
    labName: null,
    labDate: null,
  },
  {
    id: 2,
    userId: 4,
    userName: "Ananya Iyer",
    type: "fertility",
    fileName: "Fertility_Panel_Ananya_June2025.pdf",
    fileUrl: "/uploads/fertility-panel-2.pdf",
    uploadedAt: "2025-06-30T11:00:00Z",
    doctorNotes: "AMH level: 2.1 ng/mL — within normal range for age 32. AFC: 14 follicles. Good candidate for egg freezing.",
    recommendations: "Proceed with controlled ovarian stimulation protocol. Start prenatal vitamins. Avoid smoking and alcohol.",
    isLabBooked: false,
    labName: null,
    labDate: null,
  },
  {
    id: 3,
    userId: 6,
    userName: "Kavita Reddy",
    type: "metropolis",
    fileName: "Metropolis_FullPanel_Kavita.pdf",
    fileUrl: "/uploads/metropolis-3.pdf",
    uploadedAt: "2025-06-20T14:00:00Z",
    doctorNotes: "All parameters normal. Ready for stimulation cycle.",
    recommendations: "Initiate FSH injections as per protocol. Monitor via ultrasound on Day 2 and Day 6.",
    isLabBooked: true,
    labName: "Metropolis Healthcare",
    labDate: "2025-06-18T08:00:00Z",
  },
];

// ── COMMUNITY POSTS ────────────────────────────────────────────────────────
export const communityPosts: CommunityPost[] = [
  {
    id: 1,
    title: "My egg freezing journey — 3 months in",
    content: "I completed my second retrieval cycle last week and wanted to share what I learned. The stimulation phase was harder than I expected emotionally, not just physically. Having a support system makes such a difference...",
    category: "Egg Freezing Experience",
    isAnonymous: false,
    authorName: "Kavita Reddy",
    upvotes: 47,
    commentCount: 12,
    createdAt: "2025-06-29T10:00:00Z",
  },
  {
    id: 2,
    title: "AMH 1.2 at 34 — is egg freezing still viable?",
    content: "Just got my AMH results back and I'm worried. My doctor says it's low for my age. Has anyone else frozen eggs with low AMH? Would love to hear from people in similar situations...",
    category: "AMH Discussions",
    isAnonymous: true,
    authorName: "Anonymous",
    upvotes: 89,
    commentCount: 31,
    createdAt: "2025-06-27T15:00:00Z",
  },
  {
    id: 3,
    title: "How I funded my fertility preservation — full breakdown",
    content: "Total cost for my two cycles: ₹3.8L. Here's exactly how I managed it — SIP savings, the HDFC medical loan, and my company's fertility benefit. Happy to share the spreadsheet...",
    category: "Financial Planning",
    isAnonymous: false,
    authorName: "Ananya Iyer",
    upvotes: 134,
    commentCount: 28,
    createdAt: "2025-06-25T09:00:00Z",
  },
  {
    id: 4,
    title: "Telling my employer about egg freezing — my experience",
    content: "I work at a startup and was terrified to bring this up. Sharing my conversation and what happened — it might help others think through whether to disclose or not...",
    category: "Career Planning",
    isAnonymous: false,
    authorName: "Priya Sharma",
    upvotes: 67,
    commentCount: 19,
    createdAt: "2025-06-22T11:00:00Z",
  },
  {
    id: 5,
    title: "Recovery after retrieval — what nobody told me",
    content: "The retrieval itself went smoothly but the 48 hours after were rough. Bloating, mood swings, exhaustion. Here's what helped me and what I wish I had prepared...",
    category: "Recovery Stories",
    isAnonymous: true,
    authorName: "Anonymous",
    upvotes: 92,
    commentCount: 23,
    createdAt: "2025-06-20T16:00:00Z",
  },
  {
    id: 6,
    title: "Comparing clinics in Mumbai — honest review",
    content: "I consulted at 4 different clinics before choosing. Here are my notes on pricing, staff attitude, transparency of protocols, and success rates shared...",
    category: "Egg Freezing Experience",
    isAnonymous: false,
    authorName: "Meera Nair",
    upvotes: 55,
    commentCount: 14,
    createdAt: "2025-06-18T13:00:00Z",
  },
];

// ── COMMENTS ───────────────────────────────────────────────────────────────
export const comments: Comment[] = [
  {
    id: 1,
    postId: 1,
    content: "Thank you for sharing this. The emotional component is something a lot of people underestimate. How did you manage work during the stimulation phase?",
    authorName: "Ananya Iyer",
    isAnonymous: false,
    createdAt: "2025-06-29T11:00:00Z",
  },
  {
    id: 2,
    postId: 1,
    content: "My experience was similar. Day 6-9 of stimulation was the hardest. The bloating was intense. It does get better!",
    authorName: "Anonymous",
    isAnonymous: true,
    createdAt: "2025-06-29T12:00:00Z",
  },
  {
    id: 3,
    postId: 2,
    content: "AMH 1.2 at 34 is low-normal but absolutely not a dealbreaker. I froze 9 eggs with AMH of 0.9 at 36. Talk to a specialist — the number of follicles (AFC) matters just as much.",
    authorName: "Kavita Reddy",
    isAnonymous: false,
    createdAt: "2025-06-27T16:00:00Z",
  },
  {
    id: 4,
    postId: 3,
    content: "Would love that spreadsheet! Could you share it in the Financial Planning resources?",
    authorName: "Priya Sharma",
    isAnonymous: false,
    createdAt: "2025-06-25T10:00:00Z",
  },
];

// ── MESSAGE THREADS ────────────────────────────────────────────────────────
export const messageThreads: MessageThread[] = [
  {
    id: 1,
    userId: 1,
    counterpartId: 2,
    counterpartName: "Dr. Jatin Shah",
    counterpartRole: "doctor",
    lastMessage: "Please upload your AMH report before our next consultation.",
    lastMessageAt: "2025-07-02T14:30:00Z",
    unreadCount: 1,
  },
  {
    id: 2,
    userId: 1,
    counterpartId: 3,
    counterpartName: "EFFF Support Team",
    counterpartRole: "support",
    lastMessage: "Your query has been escalated to our senior advisor.",
    lastMessageAt: "2025-07-01T10:00:00Z",
    unreadCount: 0,
  },
];

export const messages: Message[] = [
  {
    id: 1,
    threadId: 1,
    senderId: 2,
    senderName: "Dr. Jatin Shah",
    content: "Hello Priya! I've reviewed your profile. Looking forward to our consultation on July 10th.",
    sentAt: "2025-07-01T10:00:00Z",
    isOwn: false,
  },
  {
    id: 2,
    threadId: 1,
    senderId: 1,
    senderName: "Priya Sharma",
    content: "Thank you, Dr. Shah. I have a few questions about the AMH test — do I need to fast before it?",
    sentAt: "2025-07-01T10:15:00Z",
    isOwn: true,
  },
  {
    id: 3,
    threadId: 1,
    senderId: 2,
    senderName: "Dr. Jatin Shah",
    content: "No fasting required for AMH. It can be done on any day of your cycle. Please upload your AMH report before our next consultation.",
    sentAt: "2025-07-02T14:30:00Z",
    isOwn: false,
  },
  {
    id: 4,
    threadId: 2,
    senderId: 1,
    senderName: "Priya Sharma",
    content: "Hi, I have a question about upgrading from Platinum to FemmeElite. What does the Dedicated Relationship Manager actually do?",
    sentAt: "2025-06-30T15:00:00Z",
    isOwn: true,
  },
  {
    id: 5,
    threadId: 2,
    senderId: 3,
    senderName: "EFFF Support Team",
    content: "Your query has been escalated to our senior advisor.",
    sentAt: "2025-07-01T10:00:00Z",
    isOwn: false,
  },
];

// ── WEBINARS ───────────────────────────────────────────────────────────────
export const webinars: Webinar[] = [
  {
    id: 1,
    title: "Understanding AMH & What Your Numbers Mean",
    description: "Join Dr. Jatin Shah for a deep dive into Anti-Mullerian Hormone, what your results mean for fertility preservation, and what to do next.",
    type: "webinar",
    speaker: "Dr. Jatin Shah",
    date: "2025-07-15T18:00:00Z",
    duration: 90,
    price: 999,
    registeredCount: 142,
    maxCapacity: 200,
    isRegistered: true,
    imageUrl: null,
    meetingUrl: "https://meet.example.com/efff-amh-webinar",
    location: null,
    createdAt: "2025-06-01T00:00:00Z",
  },
  {
    id: 2,
    title: "Egg Freezing Finance Masterclass",
    description: "Everything you need to know about funding your fertility journey — loans, SIP strategies, employer benefits, and tax savings.",
    type: "seminar",
    speaker: "Rajesh Mehta, CFP",
    date: "2025-07-22T10:00:00Z",
    duration: 180,
    price: 2499,
    registeredCount: 67,
    maxCapacity: 100,
    isRegistered: false,
    imageUrl: null,
    meetingUrl: null,
    location: "EFFF Club, Bandra West, Mumbai",
    createdAt: "2025-06-05T00:00:00Z",
  },
  {
    id: 3,
    title: "Emotional Wellness During Fertility Treatment",
    description: "A candid conversation about the mental and emotional journey of fertility preservation with our counselling team.",
    type: "webinar",
    speaker: "Dr. Meghna Patel, Psychologist",
    date: "2025-08-05T19:00:00Z",
    duration: 60,
    price: 499,
    registeredCount: 88,
    maxCapacity: 300,
    isRegistered: false,
    imageUrl: null,
    meetingUrl: "https://meet.example.com/efff-wellness",
    location: null,
    createdAt: "2025-06-10T00:00:00Z",
  },
  {
    id: 4,
    title: "Egg Freezing 101 — Everything You Need to Know",
    description: "The definitive beginner's guide to egg freezing — the science, the process, the costs, and what to expect.",
    type: "webinar",
    speaker: "Dr. Sunita Rao",
    date: "2025-06-10T18:00:00Z",
    duration: 90,
    price: 799,
    registeredCount: 215,
    maxCapacity: 250,
    isRegistered: true,
    imageUrl: null,
    meetingUrl: "https://meet.example.com/efff-101",
    location: null,
    createdAt: "2025-05-01T00:00:00Z",
  },
];

// ── SIP PLANS ──────────────────────────────────────────────────────────────
export const sipPlans: SipPlan[] = [
  {
    id: 1,
    userId: 1,
    monthlyContribution: 15000,
    goalAmount: 400000,
    currentSaved: 120000,
    progressPercent: 30,
    estimatedCompletionDate: "2027-01-15T00:00:00Z",
    startDate: "2024-11-15T00:00:00Z",
    bankName: "HDFC Bank",
  },
  {
    id: 2,
    userId: 4,
    monthlyContribution: 8000,
    goalAmount: 350000,
    currentSaved: 56000,
    progressPercent: 16,
    estimatedCompletionDate: "2028-04-10T00:00:00Z",
    startDate: "2025-01-10T00:00:00Z",
    bankName: "ICICI Bank",
  },
];

// ── LOAN OFFERS ────────────────────────────────────────────────────────────
export const loanOffers: LoanOffer[] = [
  {
    id: 1,
    bankName: "HDFC Bank",
    interestRate: 10.5,
    minEmi: 8833,
    maxTenureMonths: 60,
    maxAmount: 500000,
    eligibilityCriteria: "Salaried/Self-employed, min income ₹25,000/month, age 21-60",
    processingFee: 1.5,
    logoUrl: null,
  },
  {
    id: 2,
    bankName: "Bajaj Finance",
    interestRate: 12.0,
    minEmi: 9256,
    maxTenureMonths: 48,
    maxAmount: 400000,
    eligibilityCriteria: "Salaried, min income ₹20,000/month, age 23-58",
    processingFee: 2.0,
    logoUrl: null,
  },
  {
    id: 3,
    bankName: "ICICI Bank",
    interestRate: 11.5,
    minEmi: 8744,
    maxTenureMonths: 60,
    maxAmount: 600000,
    eligibilityCriteria: "Salaried/Self-employed, min income ₹30,000/month, age 21-65",
    processingFee: 1.25,
    logoUrl: null,
  },
  {
    id: 4,
    bankName: "Axis Bank",
    interestRate: 13.0,
    minEmi: 9512,
    maxTenureMonths: 36,
    maxAmount: 300000,
    eligibilityCriteria: "Salaried, min income ₹18,000/month, age 21-60",
    processingFee: 1.75,
    logoUrl: null,
  },
];

// ── SUPPORT TICKETS ────────────────────────────────────────────────────────
export const supportTickets: SupportTicket[] = [
  {
    id: 1,
    userId: 1,
    userName: "Priya Sharma",
    subject: "Upgrade from Platinum to FemmeElite",
    message: "I would like to upgrade my membership. Can you please walk me through the process and the additional benefits?",
    status: "in_progress",
    createdAt: "2025-06-30T15:00:00Z",
  },
  {
    id: 2,
    userId: 4,
    userName: "Ananya Iyer",
    subject: "SIP plan modification — increase monthly amount",
    message: "I want to increase my monthly SIP contribution from ₹8,000 to ₹12,000. How do I update this?",
    status: "open",
    createdAt: "2025-07-01T09:00:00Z",
  },
  {
    id: 3,
    userId: 5,
    userName: "Meera Nair",
    subject: "Report upload not working",
    message: "I'm trying to upload my AMH report but the upload keeps failing. File size is 2.3MB PDF.",
    status: "resolved",
    createdAt: "2025-06-25T11:00:00Z",
  },
];

// ── NOTIFICATIONS ──────────────────────────────────────────────────────────
export const notifications: Notification[] = [
  {
    id: 1,
    userId: 1,
    message: "Your appointment with Dr. Jatin Shah is confirmed for July 10, 2025 at 11:00 AM.",
    type: "success",
    isRead: false,
    createdAt: "2025-07-01T09:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    message: "Upload your AMH blood report to proceed to the next journey stage.",
    type: "action",
    isRead: false,
    createdAt: "2025-07-02T08:00:00Z",
  },
  {
    id: 3,
    userId: 1,
    message: "New webinar: Understanding AMH & What Your Numbers Mean — July 15, 2025.",
    type: "info",
    isRead: true,
    createdAt: "2025-06-28T10:00:00Z",
  },
];

// ── SESSIONS ───────────────────────────────────────────────────────────────
export const sessions: Map<string, number> = new Map();

// ── COUNTERS ───────────────────────────────────────────────────────────────
export const counters = {
  appointment: appointments.length,
  report: reports.length,
  post: communityPosts.length,
  comment: comments.length,
  thread: messageThreads.length,
  message: messages.length,
  webinar: webinars.length,
  sip: sipPlans.length,
  ticket: supportTickets.length,
  notification: notifications.length,
  doctor: doctors.length,
};
